import Head from "next/head";
import { FC, PropsWithChildren } from "react";

import { Footer, Navbar } from "../../common";

const PageLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <div className="mx-auto max-w-7xl px-4 space-y-8 sm:px-6 lg:px-8">
        <Head>
          <title>Personal Blog - Takao Kishimoto</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="relative bg-white pb-8 lg:w-full lg:max-w-2xl">
          <Navbar />
        </div>

        <div className="mx-auto max-w-2xl px-4 lg:max-w-7xl">{children}</div>
      </div>
      <Footer />
    </>
  );
};

export default PageLayout;
